---
- name: lamp_web_ubuntu | Install web packages on the Ubuntu server
  ansible.builtin.apt:
    name: "{{ ubuntu_web_packages }}"
    state: latest

- name: lamp_web_ubuntu | Add web port to UFW
  community.general.ufw:
    port: "{{ web_port }}"
    proto: tcp
    state: enabled

- name: lamp_web_ubuntu | Change default landing page for the website
  ansible.builtin.replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: 'index.html'
    replace: 'index.php'

- name: lamp_web_ubuntu | Clone a github repository for web page
  ansible.builtin.git:
    repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
    dest: /var/www/html/
    clone: yes
    update: yes
    force: yes

- name: lamp_web_ubuntu | Change db to localhost in the index.php file
  ansible.builtin.replace:
    path: /var/www/html/index.php
    regexp: '172.20.1.101'
    replace: 'localhost'

- name: lamp_web_ubuntu | Restart the httpd service
  ansible.builtin.service:
    name: httpd
    state: restarted
    enabled: true
