---
- name: lamp_web_rhel | Install web packages on the RHEL based server
  ansible.builtin.yum:
    name: "{{ rhel_web_packages }}"
    state: latest

- name: lamp_web_rhel | Add web port to firewall
  ansible.posix.firewalld:
    port: "{{ web_port }}/tcp"
    state: enabled
    immediate: true
    permanent: true

- name: lamp_web_rhel | Get the list of files present inside /var/www/html/
  ansible.builtin.find:
    paths: /var/www/html/
    patterns: (?i).*
    use_regex: true
  register: reg_folder_contents

- name: lamp_web_rhel | Cleanup the directory contents
  when: reg_folder_contents.files | length > 0
  ansible.builtin.file:
    path: "{{ file_item.path }}"
    state: absent
  loop: "{{ reg_folder_contents.files }}"
  loop_control:
    loop_var: file_item

- name: lamp_web_rhel | Clone a github repository for web page
  ansible.builtin.git:
    repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
    dest: /var/www/html/
    clone: yes
    update: yes
    force: yes

- name: lamp_web_rhel | Change db to localhost in the index.php file
  ansible.builtin.replace:
    path: /var/www/html/index.php
    regexp: '172.20.1.101'
    replace: 'localhost'

- name: lamp_web_rhel | Change default landing page for the website
  ansible.builtin.replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: 'index.html'
    replace: 'index.php'
  notify: Restart httpd

- name: lamp_web_rhel | Display the role level variable
  debug:
    msg: "{{ role_level_variable}}"
