---
- name: lamp_web_ubuntu | Install web packages on the Ubuntu server
  ansible.builtin.apt:
    name: "{{ ubuntu_web_packages }}"
    state: latest

- name: lamp_web_ubuntu | Add apache2 to UFW
  community.general.ufw:
    rule: allow
    port: "{{ web_port }}"
    proto: tcp

- name: lamp_web_ubuntu | Get the list of files present inside /var/www/html/
  find:
    paths: /var/www/html/
    patterns: (?i).*
    use_regex: true
  register: reg_folder_contents

- name: lamp_web_ubuntu | Cleanup the directory contents
  file:
    path: "{{ path_item.path }}"
    state: absent
  loop: "{{ reg_folder_contents.files }}"
  loop_control:
    loop_var: path_item

- name: lamp_web_ubuntu | Clone a github repository for web page
  ansible.builtin.git:
    repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
    dest: /var/www/html/
    clone: yes
    update: yes
    force: yes

- name: lamp_web_ubuntu | Change db to localhost in the index.php file
  ansible.builtin.replace:
    path: /var/www/html/index.php
    regexp: '172.20.1.101'
    replace: 'localhost'
  notify: Restart apache2
