---
- name: Play to install nginx and start the service
  hosts: al88.example.com
  gather_facts: false
  become: true
  become_method: sudo
  become_user: root
  vars:
    app_name: nginx
  tasks:
    - name: Install nginx
      yum:
        name: "{{ app_name }}"
        state: latest
    
    - name: Start the service nginx
      service:
        name: nginx
        state: started
        enabled: true
    
- name: Play to check nginx connectivity 
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Check if the website is running
      uri:
        url: "http://192.168.56.15"
        status_code: 200
      register: reg_localhost
    
    - name: Display the output
      debug:
        msg: "{{ reg_localhost }}"
