---
- name: Install common packages on the server
  ansible.builtin.yum:
    name: "{{ common_packages }}"
    state: latest

- name: Start and enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
