---
- name: lamp_main | Playbook to install LAMP stack on Linux
  hosts: rl87.example.com
  gather_facts: false
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: lamp_main | Include the vars file
      ansible.builtin.include_vars:
        file: /home/murali/ansible_and_python/playbooks/split_vars.yml

    - name: lamp_main | Include Common Tasks
      ansible.builtin.include_tasks:
        file: lamp_common.yml

    - name: lamp_main | Include DB Tasks
      ansible.builtin.include_tasks:
        file: lamp_db.yml

    - name: lamp_main | Include Web Tasks
      ansible.builtin.include_tasks:
        file: lamp_web.yml
    
- name: lamp_main | Check connectivity to the website
  hosts: localhost
  gather_facts: false
  tasks:
    - name: lamp_main | Include Check Task
      ansible.builtin.include_tasks:
        file: lamp_check.yml
