---
- name: lamp_call_role | Playbook to install LAMP stack on Linux
  hosts: all
  gather_facts: true
  tasks:
    - name: lamp_call_role | Include the vars file
      ansible.builtin.include_vars:
        file: playbooks/role_vars.yml

    - name: lamp_call_role | Include Common Tasks on Rocky
      when: ansible_distribution_file_variety == "RedHat"
      ansible.builtin.include_role:
        name: common_role
        tasks_from: lamp_common_rhel.yml

    - name: lamp_call_role | Include Common Tasks on Ubuntu
      when: ansible_distribution_file_variety == "Debian"
      ansible.builtin.include_role:
        name: common_role
        tasks_from: lamp_common_ubuntu.yml

    - name: lamp_call_role | Include DB Tasks on Rocky
      when: ansible_distribution_file_variety == "RedHat"
      ansible.builtin.include_role:
        name: db_role
        tasks_from: lamp_db_rhel.yml

    - name: lamp_call_role | Include DB Tasks on Ubuntu
      when: ansible_distribution_file_variety == "Debian"
      ansible.builtin.include_role:
        name: db_role
        tasks_from: lamp_db_ubuntu.yml

    - name: lamp_call_role | Include Web Tasks on Rocky
      when: ansible_distribution_file_variety == "RedHat"
      ansible.builtin.include_role:
        name: web_role
        tasks_from: lamp_web_rhel.yml

    - name: lamp_call_role | Include Web Tasks on Ubuntu
      when: ansible_distribution_file_variety == "Debian"
      ansible.builtin.include_role:
        name: web_role
        tasks_from: lamp_web_ubuntu.yml
    
- name: lamp_call_role | Check connectivity to the website
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: lamp_call_role | Include Check Task for both the servers
      ansible.builtin.include_tasks:
        file: lamp_check_role_run.yml
