---
- name: lamp_common | Install common packages on the server
  ansible.builtin.yum:
    name: "{{ common_packages }}"
    state: latest

- name: lamp_common | Start and enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
